<a href="https://colab.research.google.com/github/ankityadav2193/machine_learning-projects/blob/main/Spotify_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
sns.set()
%matplotlib inline

In [3]:
data=pd.read_csv('/content/spotify.csv')

In [4]:
data.head()

acousticness                    artists  ...  valence  year
0      0.991000            ['Mamie Smith']  ...   0.6340  1920
1      0.643000  ["Screamin' Jay Hawkins"]  ...   0.9500  1920
2      0.993000            ['Mamie Smith']  ...   0.6890  1920
3      0.000173        ['Oscar Velazquez']  ...   0.0422  1920
4      0.295000                   ['Mixe']  ...   0.2990  1920

[5 rows x 19 columns]

In [5]:
data.shape

(174389, 19)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174389 entries, 0 to 174388
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   acousticness      174389 non-null  float64
 1   artists           174389 non-null  object 
 2   danceability      174389 non-null  float64
 3   duration_ms       174389 non-null  int64  
 4   energy            174389 non-null  float64
 5   explicit          174389 non-null  int64  
 6   id                174389 non-null  object 
 7   instrumentalness  174389 non-null  float64
 8   key               174389 non-null  int64  
 9   liveness          174389 non-null  float64
 10  loudness          174389 non-null  float64
 11  mode              174389 non-null  int64  
 12  name              174389 non-null  object 
 13  popularity        174389 non-null  int64  
 14  release_date      174389 non-null  object 
 15  speechiness       174389 non-null  float64
 16  tempo             17

In [7]:
data.describe()

acousticness   danceability  ...        valence           year
count  174389.000000  174389.000000  ...  174389.000000  174389.000000
mean        0.499228       0.536758  ...       0.524533    1977.061764
std         0.379936       0.176025  ...       0.264477      26.907950
min         0.000000       0.000000  ...       0.000000    1920.000000
25%         0.087700       0.414000  ...       0.311000    1955.000000
50%         0.517000       0.548000  ...       0.536000    1977.000000
75%         0.895000       0.669000  ...       0.743000    1999.000000
max         0.996000       0.988000  ...       1.000000    2021.000000

[8 rows x 15 columns]

In [8]:
data.isnull().sum()

acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
valence             0
year                0
dtype: int64

In [9]:
df = data.drop(['id','name', 'artists', 'release_date', 'year'],axis=1)

In [10]:
df.head()

acousticness  danceability  duration_ms  ...  speechiness    tempo  valence
0      0.991000         0.598       168333  ...       0.0936  149.976   0.6340
1      0.643000         0.852       150200  ...       0.0534   86.889   0.9500
2      0.993000         0.647       163827  ...       0.1740   97.600   0.6890
3      0.000173         0.730       422087  ...       0.0425  127.997   0.0422
4      0.295000         0.704       165224  ...       0.0768  122.076   0.2990

[5 rows x 14 columns]

In [12]:
df.corr()

acousticness  danceability  ...     tempo   valence
acousticness          1.000000     -0.263217  ... -0.223840 -0.166968
danceability         -0.263217      1.000000  ...  0.005479  0.536713
duration_ms          -0.089169     -0.100757  ... -0.008182 -0.183199
energy               -0.750852      0.204838  ...  0.266448  0.326418
explicit             -0.208176      0.200842  ...  0.008075 -0.009275
instrumentalness      0.221956     -0.215589  ... -0.068656 -0.219188
key                  -0.028028      0.026266  ...  0.005009  0.025592
liveness             -0.029654     -0.110033  ...  0.008586 -0.005781
loudness             -0.546639      0.249541  ...  0.217914  0.302520
mode                  0.064633     -0.048358  ...  0.002438  0.021592
popularity           -0.396744      0.123746  ...  0.094985  0.063471
speechiness          -0.022437      0.239962  ... -0.033530  0.050600
tempo                -0.223840      0.005479  ...  1.000000  0.163118
valence              -0.166968      0.536713  ...  0.163118  1.000000

[14 rows x 14 columns]

In [16]:
df.dtypes

acousticness        float64
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
popularity            int64
speechiness         float64
tempo               float64
valence             float64
dtype: object

In [14]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler

In [18]:
minmax =MinMaxScaler()
x=minmax.fit_transform(df)

In [20]:
x

array([[0.99497992, 0.60526316, 0.03063657, ..., 0.09639547, 0.61590016,
        0.634     ],
       [0.64558233, 0.86234818, 0.02723665, ..., 0.05499485, 0.35682342,
        0.95      ],
       [0.99698795, 0.6548583 , 0.0297917 , ..., 0.1791967 , 0.40080983,
        0.689     ],
       ...,
       [0.80923695, 0.6791498 , 0.03997664, ..., 0.02904222, 0.44375726,
        0.714     ],
       [0.92369478, 0.46761134, 0.04482405, ..., 0.03882595, 0.70354856,
        0.32      ],
       [0.23995984, 0.68522267, 0.03614472, ..., 0.02657055, 0.46079989,
        0.747     ]])

In [21]:
from sklearn.cluster import KMeans
kmeans=KMeans(10)
features=kmeans.fit_predict(x)


In [22]:
labels=kmeans.labels_

In [23]:
labels

array([3, 3, 1, ..., 8, 6, 9], dtype=int32)

In [24]:
data['features']=features

In [25]:
features

array([3, 3, 1, ..., 8, 6, 9], dtype=int32)

In [26]:
MinMaxScaler(data['features'])

MinMaxScaler(copy=True,
             feature_range=0         3
1         3
2         1
3         9
4         6
         ..
174384    4
174385    1
174386    8
174387    6
174388    9
Name: features, Length: 174389, dtype: int32)

In [34]:
class Spotify_Recommendation():
    def __init__(self, dataset):
        self.dataset = dataset
    def recommend(self, songs, amount=1):
        distance = []
        song = self.dataset[(self.dataset.name.str.lower() == songs.lower())].head(1).values[0]
        rec = self.dataset[self.dataset.name.str.lower() != songs.lower()]
        for songs in tqdm(rec.values):
            d = 0
            for col in np.arange(len(rec.columns)):
                if not col in [1, 6, 12, 14, 18]:
                    d = d + np.absolute(float(song[col]) - float(songs[col]))
            distance.append(d)
        rec['distance'] = distance
        rec = rec.sort_values('distance')
        columns = ['artists', 'name']
        return rec[columns][:amount]

recommendations = Spotify_Recommendation(data)
recommendations.recommend("Lovers Rock", 10)

100%|██████████| 174387/174387 [00:14<00:00, 11890.79it/s]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


artists                    name
103171              ['Barão Vermelho']            Bete Balanço
55318                    ['Shinedown']                 Save Me
16385                       ['O-Zone']       Dragostea Din Tei
11168     ['Bob Marley & The Wailers']      Positive Vibration
158441              ["Olivia O'Brien"]             Love Myself
54226   ['Naughty By Nature', 'Zhané']  Jamboree (feat. Zhané)
107163              ['Britney Spears']          My Prerogative
35098                    ['Los Askis']            ¡Ay! El Amor
85047                  ['The Outlaws']            Song For You
154257                    ['Pavement']           Blue Hawaiian